name: Deploy to EC2

on:
  push:
    branches:
      - master  # ou main

jobs:
  deploy:
    runs-on: self-hosted  # usa o runner que você instalou na EC2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21 # ou a versão que você usa

      - name: Build Go binary
        run: |
          cd api
          CGO_ENABLED=1 go build -o app .

      - name: Restart service
        run: |
          sudo systemctl restart mini-market
